# Generated by Django 5.1.3 on 2026-07-17 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='class_level',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='curriculum',
            field=models.CharField(blank=True, default='Tanzania NECTA', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='QuestionUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Number of assessments this question is featured in')),
                ('attempts_count', models.PositiveIntegerField(default=0, help_text='Total student answers for this question')),
                ('correct_count', models.PositiveIntegerField(default=0, help_text='Number of correct answers')),
                ('average_time_seconds', models.FloatField(default=0.0)),
                ('difficulty_index', models.FloatField(default=0.0, help_text='Correct Rate (0.0 to 1.0)')),
                ('discrimination_index', models.FloatField(default=0.0, help_text='Discrimination index')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usage_stats', to='content.question')),
            ],
        ),
    ]
