# Generated by Django 5.1.3 on 2026-06-26 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringConfigModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('require_webcam', models.BooleanField(default=True)),
                ('require_microphone', models.BooleanField(default=False)),
                ('require_screen_share', models.BooleanField(default=False)),
                ('browser_lockdown', models.BooleanField(default=True)),
                ('block_copy_paste', models.BooleanField(default=True)),
                ('block_right_click', models.BooleanField(default=True)),
                ('face_detection', models.BooleanField(default=True)),
                ('audio_detection', models.BooleanField(default=False)),
                ('record_video', models.BooleanField(default=True)),
                ('max_tab_switches', models.PositiveIntegerField(default=0)),
                ('max_violations_before_auto_submit', models.PositiveIntegerField(default=5)),
                ('auto_submit_on_violation', models.BooleanField(default=False)),
                ('identity_verification', models.BooleanField(default=False)),
                ('video_chunk_seconds', models.PositiveIntegerField(default=10)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_config', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'Proctoring Configuration',
            },
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('flagged', 'Flagged for Review'), ('reviewed', 'Reviewed')], default='initializing', max_length=20)),
                ('webcam_consent', models.BooleanField(default=False)),
                ('identity_verified', models.BooleanField(default=False)),
                ('video_s3_prefix', models.CharField(blank=True, default='', max_length=500)),
                ('total_video_chunks', models.PositiveIntegerField(default=0)),
                ('total_flags', models.PositiveIntegerField(default=0)),
                ('teacher_review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='assessments.assessmentattempt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces'), ('looking_away', 'Looking Away'), ('tab_switch', 'Tab Switched'), ('fullscreen_exit', 'Exited Fullscreen'), ('audio_detected', 'Audio/Voice Detected'), ('copy_paste', 'Copy/Paste Attempted'), ('dev_tools', 'Developer Tools'), ('right_click', 'Right Click'), ('screenshot', 'Screenshot Attempt'), ('window_blur', 'Window Lost Focus'), ('shortcut_blocked', 'Keyboard Shortcut'), ('other', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField()),
                ('confidence', models.FloatField(default=1.0)),
                ('video_chunk_index', models.PositiveIntegerField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_flags', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='proctoring.proctoringsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
