# Generated by Django 5.1.3 on 2026-07-12 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('require_webcam', models.BooleanField(default=True)),
                ('require_microphone', models.BooleanField(default=True)),
                ('require_fullscreen', models.BooleanField(default=True)),
                ('block_copy_paste', models.BooleanField(default=True)),
                ('block_right_click', models.BooleanField(default=True)),
                ('block_devtools', models.BooleanField(default=True)),
                ('require_identity_verification', models.BooleanField(default=True)),
                ('max_tab_switches', models.PositiveIntegerField(default=0, help_text='Number of allowed tab switches before auto-submit or warning')),
                ('allowed_urls', models.JSONField(blank=True, default=list, help_text='List of domains allowed during open-book mode')),
                ('record_video', models.BooleanField(default=True)),
                ('record_audio', models.BooleanField(default=True)),
                ('ai_monitoring_enabled', models.BooleanField(default=True)),
                ('auto_submit_on_violation_count', models.PositiveIntegerField(blank=True, help_text='Auto-submit attempt after N critical flags', null=True)),
                ('review_period_days', models.PositiveIntegerField(default=30, help_text='Number of days to store video recordings before auto-deletion')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_config', to='assessments.assessment')),
            ],
            options={
                'verbose_name': 'Proctoring Configuration',
                'verbose_name_plural': 'Proctoring Configurations',
            },
        ),
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('identity_photo', models.ImageField(blank=True, null=True, upload_to='proctoring_verifications/')),
                ('identity_verified', models.BooleanField(default=False)),
                ('identity_verification_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending_consent', 'Pending Consent'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending_consent', max_length=20)),
                ('suspicion_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('recording_urls', models.JSONField(blank=True, default=list, help_text='List of video chunk URLs')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_reviewed', models.BooleanField(default=False)),
                ('teacher_review_notes', models.TextField(blank=True, default='')),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='assessments.assessmentattempt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_proctor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proctoring Session',
                'verbose_name_plural': 'Proctoring Sessions',
            },
        ),
        migrations.CreateModel(
            name='ProctoringFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag_type', models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away'), ('audio_detected', 'Suspicious Audio Detected'), ('tab_switch', 'Tab Switched'), ('fullscreen_exit', 'Exited Fullscreen'), ('copy_paste', 'Blocked Copy/Paste Attempt'), ('right_click', 'Blocked Right-Click Attempt'), ('devtools', 'Developer Tools Opened'), ('identity_mismatch', 'Identity Verification Mismatch'), ('other', 'Other Violation')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=15)),
                ('timestamp', models.PositiveIntegerField(help_text='Time offset in seconds from start of exam')),
                ('actual_time', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='proctoring_screenshots/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='proctoring.proctoringsession')),
            ],
            options={
                'verbose_name': 'Proctoring Flag',
                'verbose_name_plural': 'Proctoring Flags',
                'ordering': ['timestamp'],
            },
        ),
    ]
