# Generated by Django 5.1.3 on 2026-08-12 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_schooladminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='education_level',
            field=models.CharField(choices=[('primary', 'Primary'), ('secondary_o', 'O-Level Secondary'), ('secondary_a', 'A-Level Secondary'), ('college', 'College'), ('university', 'University')], default='secondary_o', max_length=20),
        ),
    ]
