# Generated by Django 5.1.3 on 2026-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to='assessments/'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='is_file_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
