# Generated by Django 5.1.3 on 2026-07-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_file_attachment_assessment_is_file_based_and_more'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='schools.classroom'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to be done by the student', null=True),
        ),
    ]
