# Generated by Django 5.1.3 on 2026-07-15 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_extractionjob_stagedquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedquestion',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staged_questions', to='assessments.assessment'),
        ),
    ]
