# Generated by Django 5.1.3 on 2026-06-26 10:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('signature', models.CharField(blank=True, default='', max_length=500)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa (Vodacom)'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halo_pesa', 'HaloPesa'), ('visa', 'Visa'), ('mastercard', 'Mastercard'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('payment_gateway', models.CharField(choices=[('flutterwave', 'Flutterwave'), ('clickpesa', 'ClickPesa'), ('azampay', 'AzamPay'), ('selcom', 'Selcom')], default='flutterwave', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_transaction_id', models.CharField(blank=True, default='', max_length=200)),
                ('gateway_reference', models.CharField(blank=True, default='', max_length=200)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('network_provider', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('receipt_url', models.URLField(blank=True, default='')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('refund_reason', models.TextField(blank=True, default='')),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=200, unique=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-initiated_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_tr_user_id_b99a80_idx'), models.Index(fields=['gateway_transaction_id'], name='payments_tr_gateway_41c502_idx')],
            },
        ),
    ]
